/* ---------------------------------------------------------
   new-york/city.js — what is true of New York.

   The fifth pack, and the cheapest of the five to build, for a reason
   worth stating: it is the only city so far that has both halves. Like
   San Francisco it publishes its facilities through Socrata; like Paris
   it publishes what is on — NYC Parks runs a real events feed with
   coordinates. Every other city has had one or neither.

   Zones are the city's own 2020 Neighborhood Tabulation Areas, which is
   the nearest thing New York has to an official answer to "what
   neighbourhood is this". Cemeteries, rail yards and airports are
   dropped; parks are kept, because Central Park is somewhere you go.
   Centroids are area-weighted rather than a mean of the vertices — a
   mean is pulled towards whichever edge was drawn in most detail, which
   on this coastline is the water.
   --------------------------------------------------------- */

const City = (() => {

  const id   = 'new-york';
  const name = 'New York';
  /* What a map search should be told, when the display name is not a place
     you can look up. "the Bay Area" finds nothing; a New York zone label is
     an NTA composite like "Annadale-Huguenot-Prince's Bay-Woodrow". */
  const searchRegion = 'New York';
  const ua   = 'allez-new-york (personal site)';

  /* ---------- what a piece of it is called ----------

     A neighbourhood, and New Yorkers say the name without the borough
     until they need to disambiguate — which is what `side` is for here.
     It holds the borough, because "which borough" is this city's version
     of the question the Bay Area pack asks with "city or Peninsula". */

  const zone = {
    one:  'neighbourhood',
    many: 'neighbourhoods',
    label: k => (zone.names[k] || k),
    display: (k, nm) => (nm || zone.names[k] || name),
    fallback: 'New York',
    allHeading: 'Everywhere',
    tile: k => (zone.names[k] || k),

    centroids: {
      'allerton': [40.86401, -73.8642],
      'alley-pond-park': [40.75222, -73.74555],
      'annadale-huguenot-prince-s-bay-woodrow': [40.52839, -74.19804],
      'arden-heights-rossville': [40.55264, -74.1969],
      'astoria-central': [40.76428, -73.92306],
      'astoria-east-woodside-north': [40.75956, -73.91031],
      'astoria-north-ditmars-steinway': [40.77741, -73.90526],
      'astoria-park': [40.77856, -73.92308],
      'auburndale': [40.75526, -73.786],
      'baisley-park': [40.67953, -73.78991],
      'barren-island-floyd-bennett-field': [40.59319, -73.89185],
      'bath-beach': [40.60426, -74.00748],
      'bay-ridge': [40.62667, -74.02993],
      'bay-terrace-clearview': [40.78186, -73.78758],
      'bayside': [40.76176, -73.7676],
      'bedford-park': [40.87356, -73.89079],
      'bedford-stuyvesant-east': [40.68662, -73.93179],
      'bedford-stuyvesant-west': [40.68896, -73.951],
      'bellerose': [40.73549, -73.72669],
      'belmont': [40.85761, -73.88705],
      'bensonhurst': [40.61326, -73.99327],
      'borough-park': [40.63294, -73.98954],
      'breezy-point-belle-harbor-rockaway-park-broad-channel': [40.57818, -73.86054],
      'brighton-beach': [40.57908, -73.96069],
      'bronx-park': [40.85783, -73.8755],
      'brooklyn-heights': [40.69547, -73.99483],
      'brownsville': [40.66405, -73.90952],
      'bushwick-east': [40.69124, -73.91297],
      'bushwick-west': [40.701, -73.92527],
      'calvert-vaux-park': [40.58435, -73.99409],
      'cambria-heights': [40.69434, -73.73555],
      'canarsie': [40.63935, -73.90146],
      'canarsie-park-pier': [40.63003, -73.88931],
      'carroll-gardens-cobble-hill-gowanus-red-hook': [40.67812, -74.00007],
      'castle-hill-unionport': [40.82453, -73.84869],
      'central-park': [40.78247, -73.96556],
      'chelsea-hudson-yards': [40.74938, -74.00115],
      'chinatown-two-bridges': [40.71286, -73.99366],
      'claremont-park': [40.84043, -73.9075],
      'claremont-village-claremont-east': [40.83758, -73.90354],
      'clinton-hill': [40.689, -73.96446],
      'co-op-city': [40.87231, -73.82627],
      'college-point': [40.7826, -73.83989],
      'concourse-concourse-village': [40.82675, -73.92172],
      'coney-island-sea-gate': [40.57697, -73.98797],
      'corona': [40.74324, -73.85928],
      'crotona-park': [40.83855, -73.89499],
      'crotona-park-east': [40.83214, -73.8887],
      'crown-heights-north': [40.67386, -73.9419],
      'crown-heights-south': [40.66675, -73.94601],
      'cunningham-park': [40.73394, -73.76881],
      'cypress-hills': [40.68253, -73.88206],
      'douglaston-little-neck': [40.76369, -73.73689],
      'downtown-brooklyn-dumbo-boerum-hill': [40.6949, -73.98583],
      'dyker-beach-park': [40.61115, -74.01893],
      'dyker-heights': [40.62396, -74.01085],
      'east-elmhurst': [40.76408, -73.8722],
      'east-flatbush-erasmus': [40.64855, -73.95014],
      'east-flatbush-farragut': [40.63915, -73.93764],
      'east-flatbush-remsen-village': [40.65622, -73.91917],
      'east-flatbush-rugby': [40.65155, -73.92975],
      'east-flushing': [40.7538, -73.80807],
      'east-harlem-north': [40.80161, -73.93744],
      'east-harlem-south': [40.79001, -73.94575],
      'east-midtown-turtle-bay': [40.75613, -73.9685],
      'east-new-york-city-line': [40.67054, -73.8661],
      'east-new-york-new-lots': [40.65973, -73.88804],
      'east-new-york-north': [40.67248, -73.88948],
      'east-village': [40.72596, -73.98209],
      'east-williamsburg': [40.7133, -73.93649],
      'eastchester-edenwald-baychester': [40.88154, -73.83657],
      'elmhurst': [40.7394, -73.87911],
      'far-rockaway-bayswater': [40.6017, -73.75655],
      'ferry-point-park-st-raymond-cemetery': [40.81662, -73.83258],
      'financial-district-battery-park-city': [40.70808, -74.01022],
      'flatbush': [40.64067, -73.95639],
      'flatbush-west-ditmas-park-parkville': [40.63653, -73.96619],
      'flatlands': [40.62627, -73.9301],
      'flushing-meadows-corona-park': [40.74055, -73.84077],
      'flushing-willets-point': [40.76021, -73.83158],
      'fordham-heights': [40.85873, -73.89913],
      'forest-hills': [40.72145, -73.84768],
      'forest-park': [40.70208, -73.85346],
      'fort-greene': [40.69117, -73.97436],
      'fresh-meadows-utopia': [40.73493, -73.78624],
      'freshkills-park-north': [40.58285, -74.17854],
      'freshkills-park-south': [40.56807, -74.1976],
      'glen-oaks-floral-park-new-hyde-park': [40.74595, -73.71096],
      'glendale': [40.70354, -73.87574],
      'gramercy': [40.73682, -73.98405],
      'grasmere-arrochar-south-beach-dongan-hills': [40.59354, -74.08127],
      'gravesend-east-homecrest': [40.59908, -73.96587],
      'gravesend-south': [40.58798, -73.97796],
      'gravesend-west': [40.59929, -73.98573],
      'great-kills-eltingville': [40.55025, -74.15497],
      'great-kills-park': [40.54578, -74.12834],
      'greenpoint': [40.7295, -73.94952],
      'greenwich-village': [40.73068, -73.99568],
      'hamilton-heights-sugar-hill': [40.82702, -73.94847],
      'harlem-north': [40.81893, -73.94091],
      'harlem-south': [40.80433, -73.9513],
      'hell-s-kitchen': [40.76417, -73.9924],
      'highbridge': [40.83686, -73.92776],
      'highbridge-park': [40.8466, -73.93023],
      'hoffman-swinburne-islands': [40.57624, -74.05314],
      'hollis': [40.71186, -73.76211],
      'howard-beach-lindenwood': [40.66004, -73.84404],
      'hunts-point': [40.81086, -73.88498],
      'inwood': [40.86605, -73.91932],
      'inwood-hill-park': [40.87238, -73.92434],
      'jackson-heights': [40.75552, -73.88634],
      'jacob-riis-park-fort-tilden-breezy-point-tip': [40.55858, -73.90412],
      'jamaica': [40.70402, -73.79558],
      'jamaica-bay-east': [40.61691, -73.81381],
      'jamaica-bay-west': [40.61024, -73.85951],
      'jamaica-estates-holliswood': [40.72073, -73.77761],
      'jamaica-hills-briarwood': [40.71189, -73.80886],
      'kensington': [40.64114, -73.97605],
      'kew-gardens': [40.70803, -73.82876],
      'kew-gardens-hills': [40.72665, -73.81979],
      'kingsbridge-heights-van-cortlandt-village': [40.87768, -73.89908],
      'kingsbridge-marble-hill': [40.88084, -73.90573],
      'kissena-park': [40.74532, -73.80488],
      'laurelton': [40.67591, -73.7445],
      'lincoln-terrace-park': [40.66686, -73.92682],
      'long-island-city-hunters-point': [40.74538, -73.94891],
      'longwood': [40.82097, -73.89656],
      'lower-east-side': [40.71696, -73.98384],
      'madison': [40.60491, -73.94814],
      'manhattanville-west-harlem': [40.81802, -73.95382],
      'mapleton-midwood-west': [40.61932, -73.97332],
      'marine-park-mill-basin-bergen-beach': [40.61498, -73.91854],
      'marine-park-plumb-island': [40.59405, -73.91625],
      'mariner-s-harbor-arlington-graniteville': [40.63133, -74.16737],
      'maspeth': [40.72306, -73.90512],
      'mcguire-fields': [40.61238, -73.89696],
      'melrose': [40.81826, -73.91285],
      'middle-village': [40.71922, -73.87813],
      'midtown-south-flatiron-union-square': [40.74404, -73.98975],
      'midtown-times-square': [40.7578, -73.98161],
      'midwood': [40.62037, -73.95559],
      'miller-field': [40.56873, -74.0973],
      'morningside-heights': [40.80946, -73.96176],
      'morris-park': [40.85179, -73.85169],
      'morrisania': [40.82729, -73.90474],
      'mott-haven-port-morris': [40.80752, -73.91724],
      'mount-eden-claremont-west': [40.84048, -73.91443],
      'mount-hope': [40.84987, -73.90442],
      'murray-hill-broadway-flushing': [40.76887, -73.81077],
      'murray-hill-kips-bay': [40.74425, -73.97595],
      'new-dorp-midland-beach': [40.57431, -74.10159],
      'new-springville-willowbrook-bulls-head-travis': [40.60372, -74.17545],
      'north-corona': [40.75405, -73.86285],
      'north-south-brother-islands': [40.79958, -73.89837],
      'norwood': [40.87714, -73.87902],
      'oakland-gardens-hollis-hills': [40.73931, -73.75458],
      'oakwood-richmondtown': [40.562, -74.12259],
      'ocean-hill': [40.67664, -73.91365],
      'old-astoria-hallets-point': [40.77209, -73.93142],
      'ozone-park': [40.67557, -73.84701],
      'ozone-park-north': [40.68456, -73.84937],
      'park-slope': [40.67183, -73.97976],
      'parkchester': [40.83775, -73.85799],
      'pelham-bay-country-club-city-island': [40.84559, -73.81154],
      'pelham-bay-park': [40.86825, -73.80788],
      'pelham-gardens': [40.86425, -73.84669],
      'pelham-parkway-van-nest': [40.8479, -73.86497],
      'pomonok-electchester-hillcrest': [40.72707, -73.80342],
      'port-richmond': [40.63383, -74.13318],
      'prospect-heights': [40.6776, -73.96757],
      'prospect-lefferts-gardens-wingate': [40.65976, -73.94796],
      'prospect-park': [40.6616, -73.96892],
      'queens-village': [40.71608, -73.74175],
      'queensboro-hill': [40.7431, -73.81968],
      'queensbridge-ravenswood-dutch-kills': [40.75832, -73.93793],
      'randall-s-island': [40.791, -73.9246],
      'rego-park': [40.72624, -73.86342],
      'richmond-hill': [40.69748, -73.83277],
      'ridgewood': [40.70567, -73.90369],
      'riverdale-spuyten-duyvil': [40.89572, -73.90879],
      'rockaway-beach-arverne-edgemere': [40.59157, -73.79631],
      'rockaway-community-park': [40.60338, -73.78052],
      'rosebank-shore-acres-park-hill': [40.61169, -74.07277],
      'rosedale': [40.65905, -73.73566],
      'sheepshead-bay-manhattan-beach-gerritsen-beach': [40.5883, -73.9415],
      'shirley-chisholm-state-park': [40.64533, -73.86674],
      'snug-harbor': [40.64259, -74.10327],
      'soho-little-italy-hudson-square': [40.72354, -74.00172],
      'soundview-bruckner-bronx-river': [40.82961, -73.87322],
      'soundview-clason-point': [40.81611, -73.8591],
      'soundview-park': [40.81644, -73.87125],
      'south-jamaica': [40.69431, -73.79173],
      'south-ozone-park': [40.6762, -73.81952],
      'south-richmond-hill': [40.69133, -73.82487],
      'south-williamsburg': [40.70324, -73.95666],
      'spring-creek-park': [40.64982, -73.8487],
      'spring-creek-starrett-city': [40.65101, -73.87639],
      'springfield-gardens-north-rochdale-village': [40.67333, -73.77205],
      'springfield-gardens-south-brookville': [40.66017, -73.76148],
      'st-albans': [40.69324, -73.76222],
      'st-george-new-brighton': [40.64219, -74.08553],
      'stuyvesant-town-peter-cooper-village': [40.73181, -73.97658],
      'sunnyside': [40.73842, -73.92644],
      'sunset-park-central': [40.64239, -74.00788],
      'sunset-park-east-borough-park-west': [40.64083, -73.99939],
      'sunset-park-west': [40.65347, -74.01011],
      'the-battery-governors-island-ellis-island-liberty-island': [40.69124, -74.02073],
      'throgs-neck-schuylerville': [40.82553, -73.8206],
      'todt-hill-emerson-hill-lighthouse-hill-manor-heights': [40.58965, -74.12827],
      'tompkinsville-stapleton-clifton-fox-hills': [40.6261, -74.07884],
      'tottenville-charleston': [40.52465, -74.23548],
      'tremont': [40.84692, -73.89176],
      'tribeca-civic-center': [40.71731, -74.00723],
      'university-heights-north-fordham': [40.86457, -73.90475],
      'university-heights-south-morris-heights': [40.85185, -73.91612],
      'upper-east-side-carnegie-hill': [40.77473, -73.96117],
      'upper-east-side-lenox-hill-roosevelt-island': [40.76497, -73.95509],
      'upper-east-side-yorkville': [40.77732, -73.94868],
      'upper-west-side-central': [40.7877, -73.97593],
      'upper-west-side-lincoln-square': [40.77485, -73.98469],
      'upper-west-side-manhattan-valley': [40.79925, -73.96731],
      'van-cortlandt-park': [40.89705, -73.88663],
      'wakefield-woodlawn': [40.89797, -73.85397],
      'washington-heights-north': [40.85647, -73.93345],
      'washington-heights-south': [40.8409, -73.94154],
      'west-farms': [40.84126, -73.87863],
      'west-new-brighton-silver-lake-grymes-hill': [40.62807, -74.1013],
      'west-village': [40.73484, -74.00591],
      'westchester-square': [40.83769, -73.84594],
      'westerleigh-castleton-corners': [40.617, -74.1288],
      'whitestone-beechhurst': [40.78838, -73.81089],
      'williamsbridge-olinville': [40.88102, -73.86072],
      'williamsburg': [40.71491, -73.95862],
      'windsor-terrace-south-slope': [40.65604, -73.98003],
      'woodhaven': [40.69148, -73.85741],
      'woodside': [40.7431, -73.90141],
      'yankee-stadium-macombs-dam-park': [40.82998, -73.92639]
    },

    names: {
      'allerton': 'Allerton',
      'alley-pond-park': 'Alley Pond Park',
      'annadale-huguenot-prince-s-bay-woodrow': 'Annadale-Huguenot-Prince\'s Bay-Woodrow',
      'arden-heights-rossville': 'Arden Heights-Rossville',
      'astoria-central': 'Astoria (Central)',
      'astoria-east-woodside-north': 'Astoria (East)-Woodside (North)',
      'astoria-north-ditmars-steinway': 'Astoria (North)-Ditmars-Steinway',
      'astoria-park': 'Astoria Park',
      'auburndale': 'Auburndale',
      'baisley-park': 'Baisley Park',
      'barren-island-floyd-bennett-field': 'Barren Island-Floyd Bennett Field',
      'bath-beach': 'Bath Beach',
      'bay-ridge': 'Bay Ridge',
      'bay-terrace-clearview': 'Bay Terrace-Clearview',
      'bayside': 'Bayside',
      'bedford-park': 'Bedford Park',
      'bedford-stuyvesant-east': 'Bedford-Stuyvesant (East)',
      'bedford-stuyvesant-west': 'Bedford-Stuyvesant (West)',
      'bellerose': 'Bellerose',
      'belmont': 'Belmont',
      'bensonhurst': 'Bensonhurst',
      'borough-park': 'Borough Park',
      'breezy-point-belle-harbor-rockaway-park-broad-channel': 'Breezy Point-Belle Harbor-Rockaway Park-Broad Channel',
      'brighton-beach': 'Brighton Beach',
      'bronx-park': 'Bronx Park',
      'brooklyn-heights': 'Brooklyn Heights',
      'brownsville': 'Brownsville',
      'bushwick-east': 'Bushwick (East)',
      'bushwick-west': 'Bushwick (West)',
      'calvert-vaux-park': 'Calvert Vaux Park',
      'cambria-heights': 'Cambria Heights',
      'canarsie': 'Canarsie',
      'canarsie-park-pier': 'Canarsie Park & Pier',
      'carroll-gardens-cobble-hill-gowanus-red-hook': 'Carroll Gardens-Cobble Hill-Gowanus-Red Hook',
      'castle-hill-unionport': 'Castle Hill-Unionport',
      'central-park': 'Central Park',
      'chelsea-hudson-yards': 'Chelsea-Hudson Yards',
      'chinatown-two-bridges': 'Chinatown-Two Bridges',
      'claremont-park': 'Claremont Park',
      'claremont-village-claremont-east': 'Claremont Village-Claremont (East)',
      'clinton-hill': 'Clinton Hill',
      'co-op-city': 'Co-op City',
      'college-point': 'College Point',
      'concourse-concourse-village': 'Concourse-Concourse Village',
      'coney-island-sea-gate': 'Coney Island-Sea Gate',
      'corona': 'Corona',
      'crotona-park': 'Crotona Park',
      'crotona-park-east': 'Crotona Park East',
      'crown-heights-north': 'Crown Heights (North)',
      'crown-heights-south': 'Crown Heights (South)',
      'cunningham-park': 'Cunningham Park',
      'cypress-hills': 'Cypress Hills',
      'douglaston-little-neck': 'Douglaston-Little Neck',
      'downtown-brooklyn-dumbo-boerum-hill': 'Downtown Brooklyn-DUMBO-Boerum Hill',
      'dyker-beach-park': 'Dyker Beach Park',
      'dyker-heights': 'Dyker Heights',
      'east-elmhurst': 'East Elmhurst',
      'east-flatbush-erasmus': 'East Flatbush-Erasmus',
      'east-flatbush-farragut': 'East Flatbush-Farragut',
      'east-flatbush-remsen-village': 'East Flatbush-Remsen Village',
      'east-flatbush-rugby': 'East Flatbush-Rugby',
      'east-flushing': 'East Flushing',
      'east-harlem-north': 'East Harlem (North)',
      'east-harlem-south': 'East Harlem (South)',
      'east-midtown-turtle-bay': 'East Midtown-Turtle Bay',
      'east-new-york-city-line': 'East New York-City Line',
      'east-new-york-new-lots': 'East New York-New Lots',
      'east-new-york-north': 'East New York (North)',
      'east-village': 'East Village',
      'east-williamsburg': 'East Williamsburg',
      'eastchester-edenwald-baychester': 'Eastchester-Edenwald-Baychester',
      'elmhurst': 'Elmhurst',
      'far-rockaway-bayswater': 'Far Rockaway-Bayswater',
      'ferry-point-park-st-raymond-cemetery': 'Ferry Point Park-St. Raymond Cemetery',
      'financial-district-battery-park-city': 'Financial District-Battery Park City',
      'flatbush': 'Flatbush',
      'flatbush-west-ditmas-park-parkville': 'Flatbush (West)-Ditmas Park-Parkville',
      'flatlands': 'Flatlands',
      'flushing-meadows-corona-park': 'Flushing Meadows-Corona Park',
      'flushing-willets-point': 'Flushing-Willets Point',
      'fordham-heights': 'Fordham Heights',
      'forest-hills': 'Forest Hills',
      'forest-park': 'Forest Park',
      'fort-greene': 'Fort Greene',
      'fresh-meadows-utopia': 'Fresh Meadows-Utopia',
      'freshkills-park-north': 'Freshkills Park (North)',
      'freshkills-park-south': 'Freshkills Park (South)',
      'glen-oaks-floral-park-new-hyde-park': 'Glen Oaks-Floral Park-New Hyde Park',
      'glendale': 'Glendale',
      'gramercy': 'Gramercy',
      'grasmere-arrochar-south-beach-dongan-hills': 'Grasmere-Arrochar-South Beach-Dongan Hills',
      'gravesend-east-homecrest': 'Gravesend (East)-Homecrest',
      'gravesend-south': 'Gravesend (South)',
      'gravesend-west': 'Gravesend (West)',
      'great-kills-eltingville': 'Great Kills-Eltingville',
      'great-kills-park': 'Great Kills Park',
      'greenpoint': 'Greenpoint',
      'greenwich-village': 'Greenwich Village',
      'hamilton-heights-sugar-hill': 'Hamilton Heights-Sugar Hill',
      'harlem-north': 'Harlem (North)',
      'harlem-south': 'Harlem (South)',
      'hell-s-kitchen': 'Hell\'s Kitchen',
      'highbridge': 'Highbridge',
      'highbridge-park': 'Highbridge Park',
      'hoffman-swinburne-islands': 'Hoffman & Swinburne Islands',
      'hollis': 'Hollis',
      'howard-beach-lindenwood': 'Howard Beach-Lindenwood',
      'hunts-point': 'Hunts Point',
      'inwood': 'Inwood',
      'inwood-hill-park': 'Inwood Hill Park',
      'jackson-heights': 'Jackson Heights',
      'jacob-riis-park-fort-tilden-breezy-point-tip': 'Jacob Riis Park-Fort Tilden-Breezy Point Tip',
      'jamaica': 'Jamaica',
      'jamaica-bay-east': 'Jamaica Bay (East)',
      'jamaica-bay-west': 'Jamaica Bay (West)',
      'jamaica-estates-holliswood': 'Jamaica Estates-Holliswood',
      'jamaica-hills-briarwood': 'Jamaica Hills-Briarwood',
      'kensington': 'Kensington',
      'kew-gardens': 'Kew Gardens',
      'kew-gardens-hills': 'Kew Gardens Hills',
      'kingsbridge-heights-van-cortlandt-village': 'Kingsbridge Heights-Van Cortlandt Village',
      'kingsbridge-marble-hill': 'Kingsbridge-Marble Hill',
      'kissena-park': 'Kissena Park',
      'laurelton': 'Laurelton',
      'lincoln-terrace-park': 'Lincoln Terrace Park',
      'long-island-city-hunters-point': 'Long Island City-Hunters Point',
      'longwood': 'Longwood',
      'lower-east-side': 'Lower East Side',
      'madison': 'Madison',
      'manhattanville-west-harlem': 'Manhattanville-West Harlem',
      'mapleton-midwood-west': 'Mapleton-Midwood (West)',
      'marine-park-mill-basin-bergen-beach': 'Marine Park-Mill Basin-Bergen Beach',
      'marine-park-plumb-island': 'Marine Park-Plumb Island',
      'mariner-s-harbor-arlington-graniteville': 'Mariner\'s Harbor-Arlington-Graniteville',
      'maspeth': 'Maspeth',
      'mcguire-fields': 'McGuire Fields',
      'melrose': 'Melrose',
      'middle-village': 'Middle Village',
      'midtown-south-flatiron-union-square': 'Midtown South-Flatiron-Union Square',
      'midtown-times-square': 'Midtown-Times Square',
      'midwood': 'Midwood',
      'miller-field': 'Miller Field',
      'morningside-heights': 'Morningside Heights',
      'morris-park': 'Morris Park',
      'morrisania': 'Morrisania',
      'mott-haven-port-morris': 'Mott Haven-Port Morris',
      'mount-eden-claremont-west': 'Mount Eden-Claremont (West)',
      'mount-hope': 'Mount Hope',
      'murray-hill-broadway-flushing': 'Murray Hill-Broadway Flushing',
      'murray-hill-kips-bay': 'Murray Hill-Kips Bay',
      'new-dorp-midland-beach': 'New Dorp-Midland Beach',
      'new-springville-willowbrook-bulls-head-travis': 'New Springville-Willowbrook-Bulls Head-Travis',
      'north-corona': 'North Corona',
      'north-south-brother-islands': 'North & South Brother Islands',
      'norwood': 'Norwood',
      'oakland-gardens-hollis-hills': 'Oakland Gardens-Hollis Hills',
      'oakwood-richmondtown': 'Oakwood-Richmondtown',
      'ocean-hill': 'Ocean Hill',
      'old-astoria-hallets-point': 'Old Astoria-Hallets Point',
      'ozone-park': 'Ozone Park',
      'ozone-park-north': 'Ozone Park (North)',
      'park-slope': 'Park Slope',
      'parkchester': 'Parkchester',
      'pelham-bay-country-club-city-island': 'Pelham Bay-Country Club-City Island',
      'pelham-bay-park': 'Pelham Bay Park',
      'pelham-gardens': 'Pelham Gardens',
      'pelham-parkway-van-nest': 'Pelham Parkway-Van Nest',
      'pomonok-electchester-hillcrest': 'Pomonok-Electchester-Hillcrest',
      'port-richmond': 'Port Richmond',
      'prospect-heights': 'Prospect Heights',
      'prospect-lefferts-gardens-wingate': 'Prospect Lefferts Gardens-Wingate',
      'prospect-park': 'Prospect Park',
      'queens-village': 'Queens Village',
      'queensboro-hill': 'Queensboro Hill',
      'queensbridge-ravenswood-dutch-kills': 'Queensbridge-Ravenswood-Dutch Kills',
      'randall-s-island': 'Randall\'s Island',
      'rego-park': 'Rego Park',
      'richmond-hill': 'Richmond Hill',
      'ridgewood': 'Ridgewood',
      'riverdale-spuyten-duyvil': 'Riverdale-Spuyten Duyvil',
      'rockaway-beach-arverne-edgemere': 'Rockaway Beach-Arverne-Edgemere',
      'rockaway-community-park': 'Rockaway Community Park',
      'rosebank-shore-acres-park-hill': 'Rosebank-Shore Acres-Park Hill',
      'rosedale': 'Rosedale',
      'sheepshead-bay-manhattan-beach-gerritsen-beach': 'Sheepshead Bay-Manhattan Beach-Gerritsen Beach',
      'shirley-chisholm-state-park': 'Shirley Chisholm State Park',
      'snug-harbor': 'Snug Harbor',
      'soho-little-italy-hudson-square': 'SoHo-Little Italy-Hudson Square',
      'soundview-bruckner-bronx-river': 'Soundview-Bruckner-Bronx River',
      'soundview-clason-point': 'Soundview-Clason Point',
      'soundview-park': 'Soundview Park',
      'south-jamaica': 'South Jamaica',
      'south-ozone-park': 'South Ozone Park',
      'south-richmond-hill': 'South Richmond Hill',
      'south-williamsburg': 'South Williamsburg',
      'spring-creek-park': 'Spring Creek Park',
      'spring-creek-starrett-city': 'Spring Creek-Starrett City',
      'springfield-gardens-north-rochdale-village': 'Springfield Gardens (North)-Rochdale Village',
      'springfield-gardens-south-brookville': 'Springfield Gardens (South)-Brookville',
      'st-albans': 'St. Albans',
      'st-george-new-brighton': 'St. George-New Brighton',
      'stuyvesant-town-peter-cooper-village': 'Stuyvesant Town-Peter Cooper Village',
      'sunnyside': 'Sunnyside',
      'sunset-park-central': 'Sunset Park (Central)',
      'sunset-park-east-borough-park-west': 'Sunset Park (East)-Borough Park (West)',
      'sunset-park-west': 'Sunset Park (West)',
      'the-battery-governors-island-ellis-island-liberty-island': 'The Battery-Governors Island-Ellis Island-Liberty Island',
      'throgs-neck-schuylerville': 'Throgs Neck-Schuylerville',
      'todt-hill-emerson-hill-lighthouse-hill-manor-heights': 'Todt Hill-Emerson Hill-Lighthouse Hill-Manor Heights',
      'tompkinsville-stapleton-clifton-fox-hills': 'Tompkinsville-Stapleton-Clifton-Fox Hills',
      'tottenville-charleston': 'Tottenville-Charleston',
      'tremont': 'Tremont',
      'tribeca-civic-center': 'Tribeca-Civic Center',
      'university-heights-north-fordham': 'University Heights (North)-Fordham',
      'university-heights-south-morris-heights': 'University Heights (South)-Morris Heights',
      'upper-east-side-carnegie-hill': 'Upper East Side-Carnegie Hill',
      'upper-east-side-lenox-hill-roosevelt-island': 'Upper East Side-Lenox Hill-Roosevelt Island',
      'upper-east-side-yorkville': 'Upper East Side-Yorkville',
      'upper-west-side-central': 'Upper West Side (Central)',
      'upper-west-side-lincoln-square': 'Upper West Side-Lincoln Square',
      'upper-west-side-manhattan-valley': 'Upper West Side-Manhattan Valley',
      'van-cortlandt-park': 'Van Cortlandt Park',
      'wakefield-woodlawn': 'Wakefield-Woodlawn',
      'washington-heights-north': 'Washington Heights (North)',
      'washington-heights-south': 'Washington Heights (South)',
      'west-farms': 'West Farms',
      'west-new-brighton-silver-lake-grymes-hill': 'West New Brighton-Silver Lake-Grymes Hill',
      'west-village': 'West Village',
      'westchester-square': 'Westchester Square',
      'westerleigh-castleton-corners': 'Westerleigh-Castleton Corners',
      'whitestone-beechhurst': 'Whitestone-Beechhurst',
      'williamsbridge-olinville': 'Williamsbridge-Olinville',
      'williamsburg': 'Williamsburg',
      'windsor-terrace-south-slope': 'Windsor Terrace-South Slope',
      'woodhaven': 'Woodhaven',
      'woodside': 'Woodside',
      'yankee-stadium-macombs-dam-park': 'Yankee Stadium-Macombs Dam Park'
    },

    /* borough */
    side: {
      'allerton': 'Bronx',
      'alley-pond-park': 'Queens',
      'annadale-huguenot-prince-s-bay-woodrow': 'Staten Island',
      'arden-heights-rossville': 'Staten Island',
      'astoria-central': 'Queens',
      'astoria-east-woodside-north': 'Queens',
      'astoria-north-ditmars-steinway': 'Queens',
      'astoria-park': 'Queens',
      'auburndale': 'Queens',
      'baisley-park': 'Queens',
      'barren-island-floyd-bennett-field': 'Brooklyn',
      'bath-beach': 'Brooklyn',
      'bay-ridge': 'Brooklyn',
      'bay-terrace-clearview': 'Queens',
      'bayside': 'Queens',
      'bedford-park': 'Bronx',
      'bedford-stuyvesant-east': 'Brooklyn',
      'bedford-stuyvesant-west': 'Brooklyn',
      'bellerose': 'Queens',
      'belmont': 'Bronx',
      'bensonhurst': 'Brooklyn',
      'borough-park': 'Brooklyn',
      'breezy-point-belle-harbor-rockaway-park-broad-channel': 'Queens',
      'brighton-beach': 'Brooklyn',
      'bronx-park': 'Bronx',
      'brooklyn-heights': 'Brooklyn',
      'brownsville': 'Brooklyn',
      'bushwick-east': 'Brooklyn',
      'bushwick-west': 'Brooklyn',
      'calvert-vaux-park': 'Brooklyn',
      'cambria-heights': 'Queens',
      'canarsie': 'Brooklyn',
      'canarsie-park-pier': 'Brooklyn',
      'carroll-gardens-cobble-hill-gowanus-red-hook': 'Brooklyn',
      'castle-hill-unionport': 'Bronx',
      'central-park': 'Manhattan',
      'chelsea-hudson-yards': 'Manhattan',
      'chinatown-two-bridges': 'Manhattan',
      'claremont-park': 'Bronx',
      'claremont-village-claremont-east': 'Bronx',
      'clinton-hill': 'Brooklyn',
      'co-op-city': 'Bronx',
      'college-point': 'Queens',
      'concourse-concourse-village': 'Bronx',
      'coney-island-sea-gate': 'Brooklyn',
      'corona': 'Queens',
      'crotona-park': 'Bronx',
      'crotona-park-east': 'Bronx',
      'crown-heights-north': 'Brooklyn',
      'crown-heights-south': 'Brooklyn',
      'cunningham-park': 'Queens',
      'cypress-hills': 'Brooklyn',
      'douglaston-little-neck': 'Queens',
      'downtown-brooklyn-dumbo-boerum-hill': 'Brooklyn',
      'dyker-beach-park': 'Brooklyn',
      'dyker-heights': 'Brooklyn',
      'east-elmhurst': 'Queens',
      'east-flatbush-erasmus': 'Brooklyn',
      'east-flatbush-farragut': 'Brooklyn',
      'east-flatbush-remsen-village': 'Brooklyn',
      'east-flatbush-rugby': 'Brooklyn',
      'east-flushing': 'Queens',
      'east-harlem-north': 'Manhattan',
      'east-harlem-south': 'Manhattan',
      'east-midtown-turtle-bay': 'Manhattan',
      'east-new-york-city-line': 'Brooklyn',
      'east-new-york-new-lots': 'Brooklyn',
      'east-new-york-north': 'Brooklyn',
      'east-village': 'Manhattan',
      'east-williamsburg': 'Brooklyn',
      'eastchester-edenwald-baychester': 'Bronx',
      'elmhurst': 'Queens',
      'far-rockaway-bayswater': 'Queens',
      'ferry-point-park-st-raymond-cemetery': 'Bronx',
      'financial-district-battery-park-city': 'Manhattan',
      'flatbush': 'Brooklyn',
      'flatbush-west-ditmas-park-parkville': 'Brooklyn',
      'flatlands': 'Brooklyn',
      'flushing-meadows-corona-park': 'Queens',
      'flushing-willets-point': 'Queens',
      'fordham-heights': 'Bronx',
      'forest-hills': 'Queens',
      'forest-park': 'Queens',
      'fort-greene': 'Brooklyn',
      'fresh-meadows-utopia': 'Queens',
      'freshkills-park-north': 'Staten Island',
      'freshkills-park-south': 'Staten Island',
      'glen-oaks-floral-park-new-hyde-park': 'Queens',
      'glendale': 'Queens',
      'gramercy': 'Manhattan',
      'grasmere-arrochar-south-beach-dongan-hills': 'Staten Island',
      'gravesend-east-homecrest': 'Brooklyn',
      'gravesend-south': 'Brooklyn',
      'gravesend-west': 'Brooklyn',
      'great-kills-eltingville': 'Staten Island',
      'great-kills-park': 'Staten Island',
      'greenpoint': 'Brooklyn',
      'greenwich-village': 'Manhattan',
      'hamilton-heights-sugar-hill': 'Manhattan',
      'harlem-north': 'Manhattan',
      'harlem-south': 'Manhattan',
      'hell-s-kitchen': 'Manhattan',
      'highbridge': 'Bronx',
      'highbridge-park': 'Manhattan',
      'hoffman-swinburne-islands': 'Staten Island',
      'hollis': 'Queens',
      'howard-beach-lindenwood': 'Queens',
      'hunts-point': 'Bronx',
      'inwood': 'Manhattan',
      'inwood-hill-park': 'Manhattan',
      'jackson-heights': 'Queens',
      'jacob-riis-park-fort-tilden-breezy-point-tip': 'Queens',
      'jamaica': 'Queens',
      'jamaica-bay-east': 'Queens',
      'jamaica-bay-west': 'Brooklyn',
      'jamaica-estates-holliswood': 'Queens',
      'jamaica-hills-briarwood': 'Queens',
      'kensington': 'Brooklyn',
      'kew-gardens': 'Queens',
      'kew-gardens-hills': 'Queens',
      'kingsbridge-heights-van-cortlandt-village': 'Bronx',
      'kingsbridge-marble-hill': 'Bronx',
      'kissena-park': 'Queens',
      'laurelton': 'Queens',
      'lincoln-terrace-park': 'Brooklyn',
      'long-island-city-hunters-point': 'Queens',
      'longwood': 'Bronx',
      'lower-east-side': 'Manhattan',
      'madison': 'Brooklyn',
      'manhattanville-west-harlem': 'Manhattan',
      'mapleton-midwood-west': 'Brooklyn',
      'marine-park-mill-basin-bergen-beach': 'Brooklyn',
      'marine-park-plumb-island': 'Brooklyn',
      'mariner-s-harbor-arlington-graniteville': 'Staten Island',
      'maspeth': 'Queens',
      'mcguire-fields': 'Brooklyn',
      'melrose': 'Bronx',
      'middle-village': 'Queens',
      'midtown-south-flatiron-union-square': 'Manhattan',
      'midtown-times-square': 'Manhattan',
      'midwood': 'Brooklyn',
      'miller-field': 'Staten Island',
      'morningside-heights': 'Manhattan',
      'morris-park': 'Bronx',
      'morrisania': 'Bronx',
      'mott-haven-port-morris': 'Bronx',
      'mount-eden-claremont-west': 'Bronx',
      'mount-hope': 'Bronx',
      'murray-hill-broadway-flushing': 'Queens',
      'murray-hill-kips-bay': 'Manhattan',
      'new-dorp-midland-beach': 'Staten Island',
      'new-springville-willowbrook-bulls-head-travis': 'Staten Island',
      'north-corona': 'Queens',
      'north-south-brother-islands': 'Bronx',
      'norwood': 'Bronx',
      'oakland-gardens-hollis-hills': 'Queens',
      'oakwood-richmondtown': 'Staten Island',
      'ocean-hill': 'Brooklyn',
      'old-astoria-hallets-point': 'Queens',
      'ozone-park': 'Queens',
      'ozone-park-north': 'Queens',
      'park-slope': 'Brooklyn',
      'parkchester': 'Bronx',
      'pelham-bay-country-club-city-island': 'Bronx',
      'pelham-bay-park': 'Bronx',
      'pelham-gardens': 'Bronx',
      'pelham-parkway-van-nest': 'Bronx',
      'pomonok-electchester-hillcrest': 'Queens',
      'port-richmond': 'Staten Island',
      'prospect-heights': 'Brooklyn',
      'prospect-lefferts-gardens-wingate': 'Brooklyn',
      'prospect-park': 'Brooklyn',
      'queens-village': 'Queens',
      'queensboro-hill': 'Queens',
      'queensbridge-ravenswood-dutch-kills': 'Queens',
      'randall-s-island': 'Manhattan',
      'rego-park': 'Queens',
      'richmond-hill': 'Queens',
      'ridgewood': 'Queens',
      'riverdale-spuyten-duyvil': 'Bronx',
      'rockaway-beach-arverne-edgemere': 'Queens',
      'rockaway-community-park': 'Queens',
      'rosebank-shore-acres-park-hill': 'Staten Island',
      'rosedale': 'Queens',
      'sheepshead-bay-manhattan-beach-gerritsen-beach': 'Brooklyn',
      'shirley-chisholm-state-park': 'Brooklyn',
      'snug-harbor': 'Staten Island',
      'soho-little-italy-hudson-square': 'Manhattan',
      'soundview-bruckner-bronx-river': 'Bronx',
      'soundview-clason-point': 'Bronx',
      'soundview-park': 'Bronx',
      'south-jamaica': 'Queens',
      'south-ozone-park': 'Queens',
      'south-richmond-hill': 'Queens',
      'south-williamsburg': 'Brooklyn',
      'spring-creek-park': 'Queens',
      'spring-creek-starrett-city': 'Brooklyn',
      'springfield-gardens-north-rochdale-village': 'Queens',
      'springfield-gardens-south-brookville': 'Queens',
      'st-albans': 'Queens',
      'st-george-new-brighton': 'Staten Island',
      'stuyvesant-town-peter-cooper-village': 'Manhattan',
      'sunnyside': 'Queens',
      'sunset-park-central': 'Brooklyn',
      'sunset-park-east-borough-park-west': 'Brooklyn',
      'sunset-park-west': 'Brooklyn',
      'the-battery-governors-island-ellis-island-liberty-island': 'Manhattan',
      'throgs-neck-schuylerville': 'Bronx',
      'todt-hill-emerson-hill-lighthouse-hill-manor-heights': 'Staten Island',
      'tompkinsville-stapleton-clifton-fox-hills': 'Staten Island',
      'tottenville-charleston': 'Staten Island',
      'tremont': 'Bronx',
      'tribeca-civic-center': 'Manhattan',
      'university-heights-north-fordham': 'Bronx',
      'university-heights-south-morris-heights': 'Bronx',
      'upper-east-side-carnegie-hill': 'Manhattan',
      'upper-east-side-lenox-hill-roosevelt-island': 'Manhattan',
      'upper-east-side-yorkville': 'Manhattan',
      'upper-west-side-central': 'Manhattan',
      'upper-west-side-lincoln-square': 'Manhattan',
      'upper-west-side-manhattan-valley': 'Manhattan',
      'van-cortlandt-park': 'Bronx',
      'wakefield-woodlawn': 'Bronx',
      'washington-heights-north': 'Manhattan',
      'washington-heights-south': 'Manhattan',
      'west-farms': 'Bronx',
      'west-new-brighton-silver-lake-grymes-hill': 'Staten Island',
      'west-village': 'Manhattan',
      'westchester-square': 'Bronx',
      'westerleigh-castleton-corners': 'Staten Island',
      'whitestone-beechhurst': 'Queens',
      'williamsbridge-olinville': 'Bronx',
      'williamsburg': 'Brooklyn',
      'windsor-terrace-south-slope': 'Brooklyn',
      'woodhaven': 'Queens',
      'woodside': 'Queens',
      'yankee-stadium-macombs-dam-park': 'Bronx'
    }
  };

  /* ---------- how long a kilometre takes ----------

     The subway, and it is the reason this is not the Bay Area's model.
     A train comes often enough that waiting for one is a fixed cost
     rather than a gamble, and it does not care about the hour in the way
     a road does. So the rush-hour penalty here lands on the car and
     barely on the train — which is the whole argument for taking it.

     Below a mile, walking wins in Manhattan and usually loses in Queens;
     the model does not know the difference and says so by being an
     estimate. Staten Island is reached by a ferry this does not model
     at all, which is honest: it is a half-hour boat and a decision. */

  const RUSH = [[7, 10], [16, 19]];

  const reach = {
    rush: RUSH,
    isPeak(when) {
      const d = when.getDay();
      if (d === 0 || d === 6) return false;
      const h = when.getHours() + when.getMinutes() / 60;
      return RUSH.some(([a, b]) => h >= a && h < b);
    },
    minutes(d, when) {
      const walk   = d < 1.6 ? d / 4.8 * 60 : Infinity;
      const subway = d < 40 ? 9 + (d / 30) * 60 : Infinity;
      const car    = 6 + (d / (this.isPeak(when) ? 14 : 28)) * 60;
      return Math.max(3, Math.round(Math.min(walk, subway, car)));
    },
    sector: 90
  };

  const centre = [40.7484, -73.9857];

  /* US federal holidays, fixed-date only. Thanksgiving and the Monday
     holidays move and are not guessed. */
  const holidays = {
    '2026-11-26': 'Thanksgiving',
    '2026-12-25': 'Christmas Day',
    '2027-01-01': "New Year's Day",
    '2027-07-04': 'Independence Day'
  };

  const shutsOnHoliday = ['bakery', 'cafe', 'shop', 'market'];

  const money = { symbol: '$', cheap: 30, format: n => `$${n}` };

  /* ---------- Luma ----------

     luma.com/nyc, 50 events on a rolling fortnight and every one of them
     geocoded. Checked and found to have none of their own:
     luma.com/new-york and luma.com/brooklyn. */
  const luma = [['discover', 'discplace-Izx1rQVSh8njYpP', 'Luma — New York']];

  /* ---------- what is on, and what turned out not to be ----------

     No municipal half, and the reason is worth writing down because the
     dataset looks perfect until you read its dates.

     `fudw-fgrp`, NYC Parks Events Listing, has titles, times, prices,
     links and — rare for an American city — coordinates, in a second
     table joined on event_id. It also stops on 28 December 2019. 74,880
     rows, none of them in this decade. It is an archive wearing a feed's
     clothes, and a collector was written against it before anybody
     checked `max(date)`.

     `tvpp-9vvx`, NYC Permitted Event Information, is the live one —
     through 2027, and with the categories that matter: 167 farmers
     markets, 166 block parties, 155 street events and 56 parades in a
     sixty-day window. What it has no trace of is coordinates. Its
     `event_location` is free text — "Harris Park: Baseball-01", or a
     street between two cross-streets — and scripts/events-city.mjs
     places each block by asking OpenStreetMap where the street meets
     its cross streets. Built 22 September 2026: 107 events worth
     walking into in sixty days, 103 of them placed. See the `permits`
     half of that script for what is kept and why.

     A university Localist calendar is deliberately absent too:
     Columbia's answers 403, NYU does not run one, and Fordham's is 89
     events a month and mostly fixtures.

     So New York is the permit register and Luma: the first for the
     greenmarkets, parades, plazas and Open Streets, the second for the
     evenings, about 30 a fortnight. */
  const events = { permits: 'tvpp-9vvx' };

  /* No municipal feed of things you could take up — the Parks events are
     dated, not recurring in the way practices.json means. Luma only. */
  const practices = { city: null };

  const views = {
    main: [
      { id: 'today',    label: 'Today' },
      { id: 'nights',   label: 'Nights' },
      { id: 'weekend',  label: 'Weekend' },
      { id: 'events',   label: 'Events' },
      { id: 'eat',      label: 'Eat' },
      { id: 'sport',    label: 'Sport' },
      { id: 'regulars', label: 'Regulars' },
      { id: 'explore',  label: 'Explore' },
      { id: 'away',     label: 'Away' }
    ],
    utility: [
      { id: 'quests', label: 'Quests' },
      { id: 'saved',  label: 'Saved' }
    ]
  };

  const weather = { lat: 40.75, lon: -73.99, tz: 'America/New_York' };

  /* All five boroughs. Staten Island is a ferry rather than a train and
     is thin in every layer, but it is New York and drawing the line
     anywhere else would be somebody's opinion rather than the city's. */
  const bbox = '40.515,-74.245,40.908,-73.701';

  const serviceWorker = false;

  /* What discover.mjs asks OpenStreetMap for, beyond the base layers.
     `buildings`: places drawn as a building outline as well as a pin. */
  const discover = { buildings: true };

  return { id, name, searchRegion, ua, bbox, discover, serviceWorker, zone, reach, centre, views,
           holidays, shutsOnHoliday, money, weather, luma, events, practices };
})();

if (typeof module !== 'undefined' && module.exports) module.exports = City;
