/* ---------------------------------------------------------
   The answers, from the site's own engine.

   Nothing here ranks anything the site doesn't rank the same way: it
   asks js/ (bundled as engine/engine.js) what the page asks, and adds
   only what the app needs on top — whether the person is at work right
   now, the order of the Today stack, the deck for two, and "after this".
   --------------------------------------------------------- */

import { CITY, SITE, bundled } from './data';

/* engine.js is CommonJS (module.exports = boot), generated by
   scripts/app-engine.mjs; required so no interop guesswork is involved. */
const engine = require('../../engine/engine');
const boot = typeof engine === 'function' ? engine : engine.default;

/* ---------- the world: records, place and ranking context ---------- */

export function makeWorld({ data, storage, where, prefs, now = new Date(), weather = null }) {
  let E, built;
  try {
    E = boot(CITY, { localStorage: storage, navigator: {}, fetch });
    built = build(E, data, where, now);
  } catch (e) {
    /* A fetched file this engine can't read: plan from what shipped. */
    console.warn('fresh data failed, using the bundled copy', e);
    E = boot(CITY, { localStorage: storage, navigator: {}, fetch });
    built = build(E, bundled(), where, now);
  }
  const { all, pool, today } = built;
  const byId = new Map(pool.map(i => [i.id, i]));
  all.forEach(i => { if (!byId.has(i.id)) byId.set(i.id, i); });
  const rank = {
    today,
    weatherMode: weather && weather.byDate[today] ? weather.byDate[today].mode : null,
    taste: E.Store.tasteWeights(pool, Object.assign({}, E.Store.prefs(), prefs)),
    exploredZones: E.Store.zones(),
    homeZone: where.zone
  };
  return { E, pool, byId, today, rank, where, weather, prefs, tierOf: E.Near.tierOf };
}

function build(E, data, where, now) {
  const today = E.Hours.clock(now).iso;
  const { all, discovered } = E.Rec.build(data, today);
  E.Near.use(all, discovered);
  E.Loc.boot(where);
  E.Loc.explore(where);
  const pool = all.concat(discovered.filter(i => E.Near.tierOf(i) !== 'found'));
  pool.forEach(i => { const m = E.Loc.minutesTo(i); if (m != null) i.minutesFromHome = m; });
  return { all, pool, today };
}

export function homeBase(data) {
  const b = Array.isArray(data.home.bases) ? data.home.bases[0] : data.home;
  return { lat: b.lat, lon: b.lon, zone: b.zone, area: b.label, label: b.label };
}

/* ---------- work hours ----------

   "What hours do you work?" is asked as a place, because people know
   that and are bad at "when are you free". The arithmetic is here:
   nine to six, Monday to Friday, on that place's clock. */
const WORK_TZ = { india: 'Asia/Kolkata', europe: 'Europe/Paris' };

function wallClock(tz, d) {
  const p = new Intl.DateTimeFormat('en-US', { timeZone: tz, weekday: 'short', hour: 'numeric', minute: 'numeric', hourCycle: 'h23' })
    .formatToParts(d).reduce((o, x) => (o[x.type] = x.value, o), {});
  return { day: p.weekday, mins: +p.hour * 60 + +p.minute };
}

export function atWork(hours, d, cityTz) {
  if (!hours || hours === 'odd' || hours === 'none') return false;
  const tz = WORK_TZ[hours] || cityTz;
  const { day, mins } = wallClock(tz, d);
  return !['Sat', 'Sun'].includes(day) && mins >= 9 * 60 && mins < 18 * 60;
}

/* When the person is next free, within the next eighteen hours. */
function nextFree(hours, now, cityTz) {
  if (!atWork(hours, now, cityTz)) return now;
  for (let m = 15; m <= 18 * 60; m += 15) {
    const t = new Date(now.getTime() + m * 60000);
    if (!atWork(hours, t, cityTz)) return t;
  }
  return null;
}

/* ---------- small facts for a card ---------- */

export const imageOf = i => !i.image ? null : /^https?:/.test(i.image) ? i.image : SITE + i.image;

export function openTill(w, i, at = new Date()) {
  if (!i.hours) return null;
  const { dow, mins } = w.E.Hours.clock(at);
  const r = (w.E.Hours.on(i.hours, dow) || []).find(([f, t]) => (t > f ? mins >= f && mins < t : mins >= f));
  /* Open round the clock says nothing worth a word. */
  if (!r || (r[0] === 0 && (r[1] === 0 || r[1] >= 1440))) return null;
  return clockWords(r[1] % 1440);
}

/* "6pm", "6.30pm", "midnight" — how a person says it, not a timetable. */
export function clockWords(mins) {
  if (mins === 0) return 'midnight';
  if (mins === 720) return 'noon';
  const h = Math.floor(mins / 60), m = mins % 60;
  return `${h % 12 || 12}${m ? '.' + String(m).padStart(2, '0') : ''}${h < 12 ? 'am' : 'pm'}`;
}

const isEvening = i => (i.labels || []).includes('afterwork') || (i.goodFor || []).includes('evening');
const isRegular = i => !!i.rhythm;
const coordsOf = (w, i) => i.coords || (i.zone && w.E.City.zone && w.E.City.zone.centroids && w.E.City.zone.centroids[i.zone]) || null;

function daysTo(fromIso, toIso) {
  return Math.round((Date.parse(toIso + 'T12:00:00') - Date.parse(fromIso + 'T12:00:00')) / 86400000);
}

/* Open at a moment, close enough to go, and not a whole-day undertaking:
   renderToday's test in js/app.js, at any moment rather than only now. */
function goable(w, at, reach = 30) {
  const iso = w.E.Hours.clock(at).iso;
  return i => w.E.Rank.isOpenOn(i, iso) &&
    !(i.hours && w.E.Hours.isOpen(i.hours, at) === false && w.E.Hours.openLaterToday(i.hours, at) === false) &&
    (i.durationMin ?? 120) <= 420 && (i.minutesFromHome ?? 99) <= reach &&
    i.commitment !== 'term' && i.commitment !== 'member';
}

/* ---------- Today: a short stack you finish ---------- */

export function todayStack(w, { profile, outings, now = new Date() }) {
  const cards = [];
  const used = new Set();
  const take = (list, n = 1) => {
    const out = [];
    for (const i of list) {
      if (out.length >= n) break;
      if (used.has(i.id) || w.E.Store.rating(i.id) === 'never') continue;
      used.add(i.id); out.push(i);
    }
    return out;
  };
  const tz = w.E.City.weather.tz;

  /* 1. Anything waiting for "how was it?" comes first: it's one tap. */
  (outings || []).filter(o => !o.verdict && o.dueAt && o.dueAt <= now.getTime()).slice(0, 1)
    .forEach(o => cards.push({ kind: 'how', key: 'how-' + o.key, outing: o }));

  /* 2. The answer for right now — or for when work ends. */
  const free = nextFree(profile.hours, now, tz);
  const working = free && free.getTime() !== now.getTime();
  const label = working ? 'afterWork' : 'rightNow';
  const at = free || now;
  const first = take(w.E.Rank.rank(w.pool, w.rank, goable(w, at)), 1)[0];
  const hour = w.E.Hours.clock(now).mins / 60;
  if (first) cards.push({ kind: 'pick', key: 'now-' + first.id, label, item: first, at: at.getTime() });
  else cards.push({ kind: 'pigeon', key: 'none', pose: hour >= 22 || hour < 6 ? 'tired' : 'lost', line: hour >= 22 || hour < 6 ? 'tired' : 'nothing' });

  /* The questions sit in the stack, after the first answer. */
  if (!profile.horizon) cards.push({ kind: 'askHorizon', key: 'ask-horizon' });
  else if (!profile.hours && (profile.opens || 0) >= 2) cards.push({ kind: 'askHours', key: 'ask-hours' });

  /* 3. Tonight: a Regular or an evening thing on today. A new arrival
     gets the Regular first — that's how people stop being new. */
  if (hour < 21) {
    const evening = w.E.Hours.instant(w.today, 18 * 60);
    const tonight = w.E.Rank.rank(w.pool, w.rank, i => isEvening(i) && goable(w, evening, 40)(i));
    const regularFirst = profile.horizon === 'moved' || profile.horizon === 'until';
    const sorted = regularFirst ? tonight.filter(isRegular).concat(tonight.filter(i => !isRegular(i))) : tonight;
    take(sorted, 1).forEach(i => cards.push({ kind: 'pick', key: 'tonight-' + i.id, label: 'tonight', item: i }));
  }

  /* 4. Only now: something that ends within the week. */
  const ending = w.E.Rank.rank(w.pool, w.rank, i => i.end && i.start && i.start <= w.today &&
    daysTo(w.today, i.end) >= 0 && daysTo(w.today, i.end) <= 7 && (i.minutesFromHome ?? 99) <= 60);
  take(ending, 1).forEach(i => cards.push({ kind: 'pick', key: 'ends-' + i.id, label: 'endsSoon', days: daysTo(w.today, i.end), item: i }));

  /* 5. From Thursday, the weekend. */
  const dow = w.E.Hours.clock(now).dow;
  if (dow >= 4 || dow === 0) cards.push({ kind: 'weekend', key: 'weekend' });

  /* 6. Two more, of different kinds, if there are good ones. Short on a
     thin day rather than padded. */
  const types = new Set(cards.filter(c => c.item).map(c => c.item.type));
  const more = w.E.Rank.rank(w.pool, w.rank, i => goable(w, now)(i) && !types.has(i.type));
  const picked = [];
  for (const i of more) {
    if (picked.length >= 2) break;
    if (picked.some(p => p.type === i.type)) continue;
    picked.push(...take([i], 1));
  }
  picked.forEach(i => cards.push({ kind: 'pick', key: 'more-' + i.id, label: 'alsoNow', item: i }));

  /* 7. The end. */
  const tomorrow = w.E.Hours.instant(addDays(w.today, 1), 9 * 60);
  const next = w.E.Rank.rank(w.pool, w.rank, i => !used.has(i.id) && goable(w, tomorrow)(i))[0];
  cards.push({ kind: 'end', key: 'end', tomorrow: next || null });
  return cards;
}

function addDays(iso, n) {
  const d = new Date(Date.parse(iso + 'T12:00:00') + n * 86400000);
  return d.toISOString().slice(0, 10);
}

/* ---------- the weekend ---------- */

export function companyPrefs(company = []) {
  const p = {};
  const c = company.filter(k => k !== 'dog');
  if (c.length) p.company = c;
  if (company.includes('dog')) p.dog = true;
  return p;
}

export function weekendPlan(w, { company = [], exclude = [], only = null, now = new Date() } = {}) {
  const prefs = Object.assign({}, w.prefs, companyPrefs(company));
  const rank = Object.assign({}, w.rank, { taste: w.E.Store.tasteWeights(w.pool, Object.assign({}, w.E.Store.prefs(), prefs)) });
  const ex = new Set(exclude);
  const pool = only ? w.pool.filter(i => only.has(i.id)) : w.pool;
  return w.E.Plan.weekend(pool, {
    date: w.today,
    origin: { lat: w.where.lat, lon: w.where.lon },
    weather: w.weather ? w.weather.byDate : null,
    now,
    rank,
    prefs,
    done: id => ex.has(id) || w.E.Store.rating(id) === 'never',
    rating: id => w.E.Store.rating(id)
  });
}

/* The deck for two: the plan's own stops, its picks, then the best of
   the rest that's open that weekend. Twelve cards. */
export function deckFor(w, plan, size = 12) {
  const seen = new Set();
  const out = [];
  const add = i => { if (i && !seen.has(i.id) && out.length < size) { seen.add(i.id); out.push(i); } };
  plan.days.forEach(d => d.stops.forEach(s => add(s.item)));
  plan.picks.forEach(p => add(p.item));
  w.E.Rank.rank(w.pool, w.rank, i => (w.E.Rank.isOpenOn(i, plan.sat) || w.E.Rank.isOpenOn(i, plan.sun)) &&
    (i.minutesFromHome ?? 99) <= 60 && i.commitment !== 'term' && i.commitment !== 'member').forEach(add);
  return out;
}

/* ---------- after this ---------- */

function km(a, b) {
  const R = 6371, r = x => x * Math.PI / 180;
  const dLat = r(b[0] - a[0]), dLon = r(b[1] - a[1]);
  const h = Math.sin(dLat / 2) ** 2 + Math.cos(r(a[0])) * Math.cos(r(b[0])) * Math.sin(dLon / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(h));
}

/* One thing within a ten-minute walk, open when they come out. */
export function afterThis(w, item, now = new Date()) {
  const here = coordsOf(w, item);
  if (!here) return null;
  const out = new Date(now.getTime() + (item.durationMin ?? 90) * 60000);
  const walk = i => { const c = coordsOf(w, i); return c ? km(here, c) * 1000 / 75 : 99; };
  const iso = w.E.Hours.clock(out).iso;
  const best = w.E.Rank.rank(w.pool, w.rank, i => i.id !== item.id && i.type !== item.type &&
    w.E.Rank.isOpenOn(i, iso) && walk(i) <= 10 && !(i.hours && w.E.Hours.isOpen(i.hours, out) === false) &&
    (i.durationMin ?? 120) <= 180)[0];
  return best ? { item: best, minutes: Math.max(1, Math.round(walk(best))) } : null;
}

export function directionsUrl(w, item, ios) {
  const c = coordsOf(w, item);
  const q = encodeURIComponent(item.title + (item.area ? ', ' + item.area : ''));
  if (c) return ios ? `http://maps.apple.com/?daddr=${c[0]},${c[1]}&q=${q}` : `https://www.google.com/maps/dir/?api=1&destination=${c[0]},${c[1]}`;
  return ios ? `http://maps.apple.com/?q=${q}` : `https://www.google.com/maps/search/?api=1&query=${q}`;
}

export const zoneName = (w, i) => (i.zone && w.E.Loc.ZONE_NAMES && w.E.Loc.ZONE_NAMES[i.zone]) || i.area || null;
