#!/usr/bin/env node
/* ---------------------------------------------------------
   app-engine.mjs — the site's engine, as one module the app can import.

   The app has to give the same answers as the page and the MCP server,
   so it runs the same files rather than a port of them. In the browser
   they are script tags sharing one scope, in a fixed order; here they
   are concatenated in that order inside one function, which is the same
   scope with a lid on. Nothing in them is edited.

   What the browser provides and the app must hand in: `localStorage`
   (synchronous — the app keeps an in-memory copy and saves it behind),
   `navigator` (for geolocation) and `fetch`.

   Also writes each city's records as one JSON file per city: the
   curated, researched, events and regulars layers. The OpenStreetMap
   index is not bundled; the app does not need 20,000 names to say what
   is worth leaving home for. Except where a note sits on one: several ★
   places are the founder's notes on a map record (Verve, Goodthing,
   Salt & Straw), and without their record the note has nothing to land
   on. Those records come along, and nothing else from the index.

   Run after touching js/ or a city's data:

     node scripts/app-engine.mjs            every city
     node scripts/app-engine.mjs bay-area   one city

   Writes app/engine/engine.js and app/engine/<city>.json. Both are
   generated: edit js/ and the data, never these.
   --------------------------------------------------------- */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadModuleFor } from './shim.mjs';
import { readShards } from './shard.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'app', 'engine');

/* The page's order, minus the interface: app.js, invaders.js and
   count.js draw or count, and the app does neither. city.js is not here
   because each city's pack is its own file, chosen at boot. */
const ENGINE = ['keys', 'location', 'state', 'weather', 'hours', 'record', 'nearby', 'scoring', 'plan'];
const EXPORTS = ['City', 'Keys', 'Loc', 'Store', 'Weather', 'Hours', 'Rec', 'Near', 'Rank', 'Plan'];

/* The same files check-plan.mjs reads, less the ones that only feed tabs
   the app does not have yet. */
const FILES = ['events', 'places', 'nightlife', 'sports', 'food', 'itineraries', 'daytrips',
               'civic', 'notable', 'editorial', 'notes', 'events-city', 'practices', 'regulars', 'home'];

const cities = fs.readdirSync(ROOT, { withFileTypes: true })
  .filter(d => d.isDirectory() && fs.existsSync(path.join(ROOT, d.name, 'city.js')))
  .map(d => d.name);
const only = process.argv[2];
if (only && !cities.includes(only)) { console.error(`No city pack called ${only}.`); process.exit(1); }

fs.mkdirSync(OUT, { recursive: true });

const read = f => fs.readFileSync(f, 'utf8');
const packs = cities.map(id => `  ${JSON.stringify(id)}: function () {\n${read(path.join(ROOT, id, 'city.js'))}\n; return City; }`);
const engine = `/* Generated by scripts/app-engine.mjs from js/ and each city.js. Do not edit. */
/* eslint-disable */
const PACKS = {
${packs.join(',\n')}
};

module.exports = function boot(cityId, env) {
  const { localStorage, navigator, fetch } = env;
  const City = PACKS[cityId]();
${ENGINE.map(f => `\n/* ---- js/${f}.js ---- */\n${read(path.join(ROOT, 'js', f + '.js'))}`).join('\n')}

  return { ${EXPORTS.join(', ')} };
};
`;
fs.writeFileSync(path.join(OUT, 'engine.js'), engine);
console.log(`app/engine/engine.js  ${(engine.length / 1024).toFixed(0)} KB, ${cities.length} packs`);

for (const id of only ? [only] : cities) {
  const dir = path.join(ROOT, id, 'data');
  const data = {};
  for (const f of FILES) {
    const p = path.join(dir, f + '.json');
    if (fs.existsSync(p)) data[f] = JSON.parse(read(p));
  }
  const noted = new Set(Object.keys((data.notes && data.notes.items) || {}));
  const Rec = loadModuleFor(id, 'record.js', 'Rec', { Loc: {} });
  const shards = await readShards(path.join(dir, 'places'));
  data.discovered = { items: shards.items.filter(p => noted.has(Rec.fromCompact(p).id)) };
  const out = JSON.stringify(data);
  fs.writeFileSync(path.join(OUT, id + '.json'), out);
  console.log(`app/engine/${id}.json  ${(out.length / 1024).toFixed(0)} KB, ${data.discovered.items.length} noted map records`);
}
